function sma = getSingleMiceStateMachine(choices,actions,times,conditions)
sma = NewStateMachine(); % Initialize new state machine description
sma = SetGlobalTimer(sma,...
                     'TimerID', 1,...
                     'Duration', times.StimulusDuration,...
                     'OnsetDelay',0,...
                     'Channel', 'BNC1',...
                     'OnsetValue',1,...
                     'OffsetValue',0); % 'PulseWidthByte',255,...
% sma = SetGlobalTimer(sma,...
%             'TimerID', 1,...
%             'Duration', times.StimulusDuration,...
%             'OnsetDelay',0); % 'PulseWidthByte',255,...

sma = AddState(sma, 'Name', 'Start', ...
            'Timer',0,...
            'StateChangeConditions', {'Tup','WaitforMouseToInitiate'},...
            'OutputActions', actions.StartAction);
sma = AddState(sma, 'Name', 'WaitforMouseToInitiate', ...
            'Timer',times.InitiationTimeout,...
            'StateChangeConditions', conditions.ZoneChangeCondition,...
            'OutputActions', actions.WaitingAction);
sma = AddState(sma, 'Name','InZoneTimer', ...
            'Timer',0,...
            'StateChangeConditions', conditions.ZoneTimerChangeCondition,...
            'OutputActions', actions.WaitingAction);
sma = AddState(sma, 'Name', 'SpontaneousStimulus', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'MouseMakingDecision'},...
        'OutputActions', actions.StimulusPresentationAction);
sma = AddState(sma, 'Name', 'MouseInZone', ...
            'Timer',0,...
            'StateChangeConditions', {'Tup', 'MouseMakingDecision'},...
            'OutputActions', actions.StimulusPresentationAction);
 sma = AddState(sma, 'Name', 'MouseMakingDecision', ...
            'Timer',times.DecisionTimeout,...
            'StateChangeConditions',conditions.MouseMakingDecisionChangeCondition,...
            'OutputActions', actions.WaitingAction);
sma = AddState(sma, 'Name', 'Reward', ...
            'Timer',choices.ValveTime,...
            'StateChangeConditions',conditions.RewardChangeCondition,...
            'OutputActions', actions.RewardAction);
 sma = AddState(sma, 'Name', 'RewardDisplayStimulus', ...
            'Timer',times.RewardStimulusTimeout,...
            'StateChangeConditions',{'Tup','customExit'},...
            'OutputActions',{});
sma = AddState(sma, 'Name', 'Punish', ...
            'Timer',times.PunishmentTimeout,...
            'StateChangeConditions',{'Tup','customExit'},...
            'OutputActions',actions.PunishOutputAction);
sma = AddState(sma, 'Name', 'customExit',...
            'Timer',times.ITI,...
            'StateChangeConditions', {'Tup','exit'},...
            'OutputActions',actions.ITIAction);
end