function sma = getNoGlassOneMouseStateMachine(choices,actions,times,conditions)
sma = NewStateMachine();
sma = SetGlobalTimer(sma,...
                     'TimerID', 1,...
                     'Duration', times.StimulusDuration,...
                     'OnsetDelay',0,...
                     'Channel', 'BNC1',...
                     'OnsetValue',1, 'OffsetValue',0);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'Start', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'WaitingforBothMiceStart'},...
    'OutputActions', actions.StartAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforBothMiceStart', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.NoGlassChangeCondition, 'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'BothMiceInZone', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'CheckZoneOut'},...
    'OutputActions', actions.StimulusPresentationAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'CheckZoneOut', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', conditions.CheckZoneOut, ...
    'OutputActions', actions.WaitingAction); 
%% Now add the different choices and outcomes here
    sma = AddState(sma, 'Name', 'BothMiceMakingDecision', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',{choices.m1CorrectChoice,  'RewardM1First',...
                                 choices.m1IncorrectChoice,'PunishM1First',...
                                 choices.m2CorrectChoice,  'RewardM2First',...
                                 choices.m2InCorrectChoice,'PunishM2First',...
                                 'Tup','customExit'},...
        'OutputActions', actions.WaitingAction);
    
    %% M1 Rewarded First, M2 Rewarded Second, Both Rewarded.
    % (Coming after BothMiceMakingDecision)
    sma = AddState(sma, 'Name', 'RewardM1First', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    %% M2 Rewarded First, M1 Rewarded Second, Both Rewarded.
    % (Coming after BothMiceMakingDecision)
    sma = AddState(sma, 'Name', 'RewardM2First', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m2CorrectValve,1, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);

      %% M1 Punished First, M2 Rewarded Second, M2RewardedM1Punished
    sma = AddState(sma, 'Name', 'PunishM1First', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction, 'AnalogIn1', ['#' 1]]);

    %% M2 Punished First, M1 Rewarded Second, M1RewardedM2Punished
    sma = AddState(sma, 'Name', 'PunishM2First', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction, 'AnalogIn1', ['#' 2] ]);

%% A (performance) trial will result in 4 possibilities: both rewarded, both punished and so on...
sma = AddState(sma, 'Name', 'BothRewarded', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'BothPunished', ...
    'Timer',times.PunishmentTimeout,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', actions.PunishOutputAction);
sma = AddState(sma, 'Name', 'customExit',...
    'Timer',times.ITI,...
    'StateChangeConditions', {'Tup','exit'},...
    'OutputActions',actions.ITIAction);
end