function sma = getTwoMiceStateMachineCooperationOutOfPoke(choices,actions,times,conditions)
sma = NewStateMachine();
sma = SetGlobalTimer(sma,...
                     'TimerID', 1,...
                     'Duration', times.StimulusDuration,...
                     'OnsetDelay',0,...
                     'Channel', 'BNC1',...
                     'OnsetValue',1, 'OffsetValue',0);
%%%%%%%%%%% Start Beatriz Added
sma = SetGlobalTimer(sma,...
                     'TimerID', 2,...
                     'Duration', times.DecisionTimeout,...
                     'OnsetDelay',0);
%                      'Channel', 'none',...
%                      'OnsetValue',1, 'OffsetValue',0);

%%%%%%%%%%% End Beatriz Added
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'Start', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'WaitingforBothMiceStart'},...
    'OutputActions', actions.StartAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforBothMiceStart', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.ZoneChangeCondition, 'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse2', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse2,...
    'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse1', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse1,...
    'OutputActions', actions.WaitingAction); 
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'BothMiceInZone', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'CheckZoneOut'},...
    'OutputActions', actions.StimulusPresentationAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'CheckZoneOut', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', conditions.CheckZoneOut, ...
    'OutputActions', [actions.WaitingAction, {'GlobalTimerTrig', 2}]);  %When one of the mice leave circle, go to BothMiceMakingDecision

%START GLOBAL TIMER, afterwards 'Tup', 'customExit'

%% Waiting for the first mouse to make a choice
    sma = AddState(sma, 'Name', 'BothMiceMakingDecision', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'CorrectM1SoftDelay'},...
                                 {choices.m2CorrectChoice,  'CorrectM2SoftDelay'},...
                                 conditions.MouseTerminateFirst,...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
    %% In case of looping over Both Mice Making decision
       sma = AddState(sma, 'Name', 'AgainBothMiceMakingDecision', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectWaiting'},...
                                 {choices.m2CorrectChoice,  'M2CorrectWaiting'},...
                                 conditions.MouseTerminate,...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
%--------------------------------------------------------------------------    
 %% M1 chose first and correctly
   %% Within soft delay: if 2 correct, both fully rewarded or, if 1 wrong both unrewarded (terminate option)
    sma = AddState(sma, 'Name', 'CorrectM1SoftDelay', ...
        'Timer',times.SoftDelay,...
        'StateChangeConditions', [{choices.OutOfPokeM1, 'OutOfPokeWindowM1'},...
                                  {choices.m2CorrectChoice, 'BothFirstRewardM1'},...
                                  conditions.MouseTerminate,...
                                  {'Tup','M1CorrectWaiting'}], ...
        'OutputActions', actions.WaitingAction);

   sma = AddState(sma, 'Name', 'OutOfPokeWindowM1', ...
        'Timer',times.OutOfPokeWindow,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'BothFirstRewardM1'},...
                                  {choices.m1CorrectChoice, 'M1CorrectWaiting'},...
                                  conditions.MouseTerminate,...
                                  {'Tup','AgainBothMiceMakingDecision'}], ...
        'OutputActions', actions.WaitingAction);
    
    
    %% After soft delay (M2 can only get PercentageRewardSecond, or if M2 wrong, both punished)
    sma = AddState(sma, 'Name', 'M1CorrectWaiting', ...
        'Timer',times.CooperationTimeout,...
        'StateChangeConditions', [{choices.OutOfPokeM1, 'OutOfPokeWindowAfterDelayM1'},...
                                  conditions.MouseTerminate,...
                                  conditions.M1CooperationOrCompetition ], ...
        'OutputActions', actions.WaitingAction);
    
    sma = AddState(sma, 'Name', 'OutOfPokeWindowAfterDelayM1', ...
        'Timer',times.OutOfPokeWindow,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'M1CorrectWaiting'},...
                                  conditions.MouseTerminate,...
                                  conditions.M1CooperationOrCompetition,...
                                  {'Tup','AgainBothMiceMakingDecision'}], ...
        'OutputActions', actions.WaitingAction);   
    

%% M2 chose first and correctly
   %% Within soft delay: if 1 correct, both fully rewarded or, if 1 wrong both unrewarded (terminate option)
    sma = AddState(sma, 'Name', 'CorrectM2SoftDelay', ...
        'Timer',times.SoftDelay,...
        'StateChangeConditions', [{choices.OutOfPokeM2, 'OutOfPokeWindowM2'},...
                                  {choices.m1CorrectChoice, 'BothFirstRewardM2'},...
                                  conditions.MouseTerminate,...
                                  {'Tup','M2CorrectWaiting'}], ...
        'OutputActions', actions.WaitingAction);

   sma = AddState(sma, 'Name', 'OutOfPokeWindowM2', ...
        'Timer',times.OutOfPokeWindow,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'BothFirstRewardM2'},...
                                  {choices.m2CorrectChoice, 'M2CorrectWaiting'},...
                                  conditions.MouseTerminate,...
                                  {'Tup','AgainBothMiceMakingDecision'}], ...
        'OutputActions', actions.WaitingAction);
    
    
    %% After soft delay (M2 can only get PercentageRewardSecond, or if M2 wrong, both punished)
    sma = AddState(sma, 'Name', 'M2CorrectWaiting', ...
        'Timer',times.CooperationTimeout,...
        'StateChangeConditions', [{choices.OutOfPokeM2, 'OutOfPokeWindowAfterDelayM2'},...
                                  conditions.MouseTerminate,...
                                  conditions.M2CooperationOrCompetition ], ...
        'OutputActions', actions.WaitingAction);
    
    sma = AddState(sma, 'Name', 'OutOfPokeWindowAfterDelayM2', ...
        'Timer',times.OutOfPokeWindow,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'M2CorrectWaiting'},...
                                  conditions.MouseTerminate,...
                                  conditions.M2CooperationOrCompetition,...
                                  {'Tup','AgainBothMiceMakingDecision'}], ...
        'OutputActions', actions.WaitingAction);   

  
%--------------------------------------------------------------------------    
    %% Mice cooperated, M1 chose first
    %% In case both answer almost simultaneously (M1 First)
    sma = AddState(sma, 'Name', 'BothFirstRewardM1', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'FullRewardM2'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'FullRewardM2', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
        %% M1 rewarded first, M2 gets PercentageRewardSecond
    sma = AddState(sma, 'Name', 'RewardM1First', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'RewardM2Second'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    
    sma = AddState(sma, 'Name', 'RewardM2Second', ...
        'Timer',choices.m2ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [conditions.RewardSecondM2 {'SoftCode',100, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);
    
%% Mice cooperated, M2 chose first
    %% In case both answer almost simultaneously (M2 first)
    sma = AddState(sma, 'Name', 'BothFirstRewardM2', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'FullRewardM1'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'FullRewardM1', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    %% M2 rewarded first, M1 gets PercentageRewardSecond
    sma = AddState(sma, 'Name', 'RewardM2First', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'RewardM1Second'},...
        'OutputActions', [{choices.m2CorrectValve,1, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'RewardM1Second', ...
        'Timer',choices.m1ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [conditions.RewardSecondM1 {'SoftCode',100, 'AnalogIn1', ['#' 1]} actions.WaitingAction]);


    %--------------------------------------------------------------------------  
    %% First one wrong, both punished    
    %% M1 Wrong First, BothPunished
    sma = AddState(sma, 'Name', 'M1WrongFirstBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', {choices.m2InCorrectChoice,'M2WrongAfterEnd',... 
                                  choices.m2CorrectChoice, 'M2CorrectAfterEnd',...
                                  'GlobalTimer2_End','BothPunished',...
                                  'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    %% M2 Wrong First, BothPunished
    sma = AddState(sma, 'Name', 'M2WrongFirstBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', {choices.m1IncorrectChoice,'M1WrongAfterEnd',... 
                                  choices.m1CorrectChoice, 'M1CorrectAfterEnd',...
                                  'GlobalTimer2_End','BothPunished',...
                                  'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
  %% Collecting second mouse choice after first wrong mouse - both punished  
    sma = AddState(sma, 'Name', 'M2WrongAfterEnd', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    sma = AddState(sma, 'Name', 'M2CorrectAfterEnd', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    sma = AddState(sma, 'Name', 'M1WrongAfterEnd', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    sma = AddState(sma, 'Name', 'M1CorrectAfterEnd', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
%--------------------------------------------------------------------------  
%% Second wrong both punished
    %% First one wrong, both punished    
    %% M1 Wrong First, BothPunished
    sma = AddState(sma, 'Name', 'M1WrongSecondBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    %% M2 Wrong First, BothPunished
    sma = AddState(sma, 'Name', 'M2WrongSecondBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
  %--------------------------------------------------------------------------      
%% A trial will result in 2 possibilities: both rewarded or both punished
sma = AddState(sma, 'Name', 'BothRewarded', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'BothPunished', ...
    'Timer',times.PunishmentTimeout,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', actions.PunishOutputAction);

sma = AddState(sma, 'Name', 'customExit',...
    'Timer',times.ITI,...
    'StateChangeConditions', {'Tup','exit'},...
    'OutputActions',actions.ITIAction);
end