function sma = getTwoMiceStateMachineStartingLine(choices,actions,times,conditions)
sma = NewStateMachine();
sma = SetGlobalTimer(sma,...
                     'TimerID', 1,...
                     'Duration', times.StimulusDuration,...
                     'OnsetDelay',0,...
                     'Channel', 'BNC1',...
                     'OnsetValue',1, 'OffsetValue',0);

sma = SetGlobalTimer(sma,...
                     'TimerID', 2,...
                     'Duration', times.DecisionTimeout,...
                     'OnsetDelay',0);
%% 1) START TRIAL
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'Start', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'WaitingforBothMiceStart'},...
    'OutputActions', actions.StartAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforBothMiceStart', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.ZoneChangeCondition, 'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse2', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse2,...
    'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse1', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse1,...
    'OutputActions', actions.WaitingAction); 
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'BothMiceInZone', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'CheckZoneOut'},...
    'OutputActions', actions.StimulusPresentationAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'CheckZoneOut', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', conditions.CheckZoneOut, ...
    'OutputActions', [actions.WaitingAction, {'GlobalTimerTrig', 2}]);  %When one of the mice leave circle, go to BothMiceMakingDecision

%--------------------------------------------------------------------------    
%% 2) CHECK FIRST CROSSING OF START LINE
%% Waiting for the first mice to cross starting line (all states dependent on crossing and not on choice)
    sma = AddState(sma, 'Name', 'BothMiceMakingDecision', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'M1CrossedWaiting'},...
                                 {choices.m2correctCross, 'M2CrossedWaiting'},...
                                 {choices.m1IncorrectCross, 'WrongCrossM1'},...
                                 {choices.m2IncorrectCross, 'WrongCrossM2'},...                                                                   
                                 {'Tup','customExit'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
      sma = AddState(sma, 'Name', 'M1CrossedWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2correctCross, 'M2CrossedSecondCorrect'},... Both mice have crossed, fastest get reward
                                 {choices.m2IncorrectCross, 'M2IncorrectCrossCollectPokes'},... M2 chose wrong, both lose       
                                 {choices.m1CorrectChoice,  'CorrectM1WaitM2Cross'},... Fastest mouse chose, waiting for second cross or disengagement                                                        
                                 {choices.m1IncorrectChoice,'M1WrongWaitM2Cross'},...                                                      
                                 {'Tup','customExit'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
    %%above its missing wrong choice bz the first but it is unlikelly!

       sma = AddState(sma, 'Name', 'M2CrossedWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'M1CrossedSecondCorrect'},... Both mice have crossed, fastest get reward
                                 {choices.m1IncorrectCross, 'M1IncorrectCrossCollectPokes'},... M2 chose wrong, both lose
                                 {choices.m2CorrectChoice,  'CorrectM2WaitM1Cross'},... Fastest mouse chose, waiting for second cross or disengagement
                                 {choices.m2IncorrectChoice,'M2WrongWaitM1Cross'},... FIX NEVER GONNA HAPPEN!!!!!                                                   
                                 {'Tup','customExit'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------    
%% 3) CHECK SECOND CROSSING OF START LINE
    % Collect second correct cross
     sma = AddState(sma, 'Name', 'M2CrossedSecondCorrect', ...
        'Timer',0,...
        'StateChangeConditions',[{'Tup','ReleaseReward'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
     sma = AddState(sma, 'Name', 'M1CrossedSecondCorrect', ...
        'Timer',0,...
        'StateChangeConditions',[{'Tup','ReleaseReward'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);    
    
 %--------------------------------------------------------------------------       
    %BOTH CROSSED CORRECTLY, COLLECT POKES (POSSIBLY REWARDED)
    sma = AddState(sma, 'Name', 'ReleaseReward', ... correct check
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'RewardM1First'},... 
                                 {choices.m2CorrectChoice,  'RewardM2First'},...
                                 {choices.m1IncorrectChoice,'IncorrectChoiceM1WaitingM2'},...
                                 {choices.m2IncorrectChoice,'IncorrectChoiceM2WaitingM1'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
 %--------------------------------------------------------------------------    
    %FIRST MOUSE CORRECT BUT WAITING FOR SECOND MOUSE TO CROSS
    sma = AddState(sma, 'Name', 'CorrectM1WaitM2Cross', ...
        'Timer',times.NoCrossTimeout,...
        'StateChangeConditions',[{choices.m2correctCross, 'CorrectCrossM2RewardM1'},... Both mice have crossed, fastest get reward
                                 {choices.m2IncorrectCross, 'M2IncorrectCrossCollectItsPoke'},... M2 chose wrong, both lose                                                                                               
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','RewardOnlyM1'}],...
        'OutputActions', actions.WaitingAction);
    
    %Register M2 cross, while rewarding M1 and then collect M2 choice
    sma = AddState(sma, 'Name', 'CorrectCrossM2RewardM1', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'CorrectCrossM2WaitPoke'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'CorrectCrossM2WaitPoke', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'RewardM2Second'} ...
                                  {choices.m2IncorrectChoice,'M2Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);

    
  %--------------------------------------------------------------------------   
%M1 chose and then M2 crossed correctly OR M2 cross wrong or M2 doesnt cross
    sma = AddState(sma, 'Name', 'CorrectM2WaitM1Cross', ...
        'Timer',times.NoCrossTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'CorrectCrossM1RewardM2'},... Both mice have crossed, fastest get reward
                                 {choices.m1IncorrectCross, 'M1IncorrectCrossCollectItsPoke'},... M2 chose wrong, both lose                                                                                               
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','RewardOnlyM2'}],...
        'OutputActions', actions.WaitingAction);
    
    %Register M2 cross, while rewarding M1 and then collect M2 choice
    sma = AddState(sma, 'Name', 'CorrectCrossM1RewardM2', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'CorrectCrossM1WaitPoke'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'CorrectCrossM1WaitPoke', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'RewardM1Second'} ...
                                  {choices.m1IncorrectChoice,'M1Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);

%--------------------------------------------------------------------------    
%% 4) RELEASE REWARD
    %% Both went to the correct side
    %% M1 First
    %this is wrong cause its been a while the first has poked and the
    %second can still get reward!!!
    sma = AddState(sma, 'Name', 'RewardM1First', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'CorrectM1SoftDelay'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'CorrectM1SoftDelay', ... within the soft delay, both get full reward
        'Timer',times.SoftDelay,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'FullRewardM2'},...
                                  {choices.m2IncorrectChoice,'M2Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','M1CorrectWaiting'}], ...
        'OutputActions', actions.WaitingAction);

    sma = AddState(sma, 'Name', 'FullRewardM2', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'M1CorrectWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'RewardM2Second'} ...
                                  {choices.m2IncorrectChoice,'M2Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}], ...
        'OutputActions', actions.WaitingAction);


    %% M2 First
    sma = AddState(sma, 'Name', 'RewardM2First', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'CorrectM2SoftDelay'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'CorrectM2SoftDelay', ... within the soft delay, both get full reward
        'Timer',times.SoftDelay,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'FullRewardM1'},...
                                  {choices.m1IncorrectChoice,'M1Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','M2CorrectWaiting'}], ...
        'OutputActions', actions.WaitingAction);

    sma = AddState(sma, 'Name', 'FullRewardM1', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', [{'GlobalTimer2_End','customExit'},...
                                 {'Tup', 'BothRewarded'}],...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'M2CorrectWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'RewardM1Second'} ...
                                  {choices.m1IncorrectChoice,'M1Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}], ...
        'OutputActions', actions.WaitingAction);
    
       
%--------------------------------------------------------------------------  
    %% One mouse gave up, reward only first
    %SECOND MOUSE DIDN'T CROSS, ONLY FIRST IS REWARDED
     sma = AddState(sma, 'Name', 'RewardOnlyM1', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', conditions.M2NoCrossTerminate,...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
     sma = AddState(sma, 'Name', 'RewardOnlyM2', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', conditions.M1NoCrossTerminate,...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
%--------------------------------------------------------------------------      
    %COLLECT CROSS AND POKE OF SECOND MOUSE    
     sma = AddState(sma, 'Name', 'CollectM2CrossLate', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m2correctCross, 'CorrectCrossM2WaitPoke'},... Both mice have crossed, fastest get reward
                                  {choices.m2IncorrectCross, 'M2IncorrectCrossCollectItsPoke'},... M2 chose wrong, both lose 
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    sma = AddState(sma, 'Name', 'CollectM1CrossLate', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m1correctCross, 'CorrectCrossM1WaitPoke'},... Both mice have crossed, fastest get reward
                                  {choices.m1IncorrectCross, 'M1IncorrectCrossCollectItsPoke'},... M2 chose wrong, both lose 
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);   

%--------------------------------------------------------------------------  
    %% First Mouse Wrong, Second Rewarded (unlikely, but who knows)
    %FIRST MOUSE CROSSED CORRECTLY BUT CHOSE WRONG, COLLECT SECOND MOUSE CROSS
     sma = AddState(sma, 'Name', 'M2WrongWaitM1Cross', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m1correctCross, 'CorrectCrossM1CollectPoke'},... Both mice have crossed, fastest get reward
                                  {choices.m1IncorrectCross, 'M1IncorrectCrossCollectItsPoke'},... M2 chose wrong, both lose 
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    %BOTH MICE CROSSED CORRECTLY, FIRST CHOSE WRONG, COLLECT SECOND CHOICE
     sma = AddState(sma, 'Name', 'CorrectCrossM1CollectPoke', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1RewardedTerminal'},...
                                 {choices.m1IncorrectChoice,'M1WrongTerminal'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    %SECOND MOUSE IS THE ONLY REWARDED
     sma = AddState(sma, 'Name', 'M1RewardedTerminal', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'M1RewardedM2Wrong'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

%-------------------------------------------------------------------------- 
    %FIRST MOUSE CROSSED CORRECTLY BUT CHOSE WRONG, COLLECT SECOND MOUSE CROSS
     sma = AddState(sma, 'Name', 'M1WrongWaitM2Cross', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m2correctCross, 'CorrectCrossM2CollectPoke'},... Both mice have crossed, fastest get reward
                                  {choices.m2IncorrectCross, 'M2IncorrectCrossCollectItsPoke'},... M2 chose wrong, both lose 
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    %BOTH MICE CROSSED CORRECTLY, FIRST CHOSE WRONG, COLLECT SECOND CHOICE
     sma = AddState(sma, 'Name', 'CorrectCrossM2CollectPoke', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M2RewardedTerminal'},...
                                 {choices.m2IncorrectChoice,'M2WrongTerminal'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    %SECOND MOUSE IS THE ONLY REWARDED
     sma = AddState(sma, 'Name', 'M2RewardedTerminal', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'M2RewardedM1Wrong'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
%% First mouse crossed correctly but chose wrong, second still has a chance

     sma = AddState(sma, 'Name', 'IncorrectChoiceM1WaitingM2', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M2RewardedTerminal'},...
                                 {choices.m2IncorrectChoice,'M2WrongTerminal'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
    
     sma = AddState(sma, 'Name', 'IncorrectChoiceM2WaitingM1', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1RewardedTerminal'},...
                                 {choices.m1IncorrectChoice,'M1WrongTerminal'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);

    %% Second mouse is slower and gets PercentageRewardSecond
    sma = AddState(sma, 'Name', 'RewardM2Second', ...
        'Timer',choices.m2ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothCorrect'},...
        'OutputActions', [conditions.RewardSecondM2 {'SoftCode',100, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'RewardM1Second', ...
        'Timer',choices.m1ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothCorrect'},...
        'OutputActions', [conditions.RewardSecondM1 {'SoftCode',100, 'AnalogIn1', ['#' 1]} actions.WaitingAction]);

%-------------------------------------------------------------------------- 
%% 5) PUNISH BOTH MICE, BUT COLLECT THEIR CHOICES
    %% One crossed wrong  
    %FIRST MOUSE CROSSED WRONG, COLLECT SECOND CROSS OR A POKE
    sma = AddState(sma, 'Name', 'WrongCrossM1', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2correctCross, 'M2CorrectCrossCollectPokes'},...
                                 {choices.m2IncorrectCross, 'M2IncorrectCrossCollectPokes'},... No one gets reward                                
                                 {choices.m1CorrectChoice,  'M1CorrectFirstCollectM2Cross'},...
                                 {choices.m1IncorrectChoice,  'M1IncorrectFirstCollectM2Cross'},...                             
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
     sma = AddState(sma, 'Name', 'WrongCrossM2', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'M1CorrectCrossCollectPokes'},...
                                 {choices.m1IncorrectCross, 'M1IncorrectCrossCollectPokes'},... No one gets reward                                
                                 {choices.m2CorrectChoice,  'M2CorrectFirstCollectM1Cross'},...
                                 {choices.m2IncorrectChoice,  'M2IncorrectFirstCollectM1Cross'},...                             
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
%-------------------------------------------------------------------------- 
    %REGISTER SECOND CROSS
    sma = AddState(sma, 'Name', 'M1CorrectCrossCollectPokes', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokes'}],...
        'OutputActions', actions.WaitingAction);   
    sma = AddState(sma, 'Name', 'M1IncorrectCrossCollectPokes', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokes'}],...
        'OutputActions', actions.WaitingAction);                         
    sma = AddState(sma, 'Name', 'M2CorrectCrossCollectPokes', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokes'}],...
         'OutputActions', actions.WaitingAction);                        
    sma = AddState(sma, 'Name', 'M2IncorrectCrossCollectPokes', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokes'}],...                                 
        'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------     
     %BOTH MICE CROSSED, COLLECT POKES
     sma = AddState(sma, 'Name', 'CollectPokes', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectFirstCollectM2Poke'},...
                                 {choices.m2CorrectChoice,  'M2CorrectFirstCollectM1Poke'},...
                                 {choices.m1IncorrectChoice,  'M1WrongFirstCollectM2Poke'},...
                                 {choices.m2IncorrectChoice,  'M2WrongFirstCollectM1Poke'},...                            
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------     
    %REGISTER FIRST POKE
    sma = AddState(sma, 'Name', 'M1CorrectFirstCollectM2Poke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM2'}],...                                 
        'OutputActions', actions.WaitingAction);
    sma = AddState(sma, 'Name', 'M1WrongFirstCollectM2Poke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM2'}],...                                 
        'OutputActions', actions.WaitingAction);
    sma = AddState(sma, 'Name', 'M2CorrectFirstCollectM1Poke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM1'}],...                                 
        'OutputActions', actions.WaitingAction);
    sma = AddState(sma, 'Name', 'M2WrongFirstCollectM1Poke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM1'}],...                                 
        'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------     
    %BOTH MICE CROSSED AND ONE POKED, COLLECT SECOND POKE
    sma = AddState(sma, 'Name', 'CollectPokeM1', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectTerminal'},...
                                 {choices.m1IncorrectChoice,  'M1WrongTerminal'},...                           
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
    sma = AddState(sma, 'Name', 'CollectPokeM2', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M2CorrectTerminal'},...
                                 {choices.m1IncorrectChoice,  'M2WrongTerminal'},...                           
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
 %--------------------------------------------------------------------------    
    %REGISTER SECOND POKE
    sma = AddState(sma, 'Name', 'M1CorrectTerminal', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    sma = AddState(sma, 'Name', 'M1WrongTerminal', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    sma = AddState(sma, 'Name', 'M2CorrectTerminal', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    sma = AddState(sma, 'Name', 'M2WrongTerminal', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
%-------------------------------------------------------------------------- 
    %REGISTER FIRST MOUSE POKE, BUT SECOND HAS NOT CROSSED YET
    sma = AddState(sma, 'Name', 'M1CorrectFirstCollectM2Cross', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectCrossM2'}],...                                 
        'OutputActions', actions.WaitingAction);    
    sma = AddState(sma, 'Name', 'M1IncorrectFirstCollectM2Cross', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectCrossM2'}],...                                 
        'OutputActions', actions.WaitingAction);    
    sma = AddState(sma, 'Name', 'M2CorrectFirstCollectM1Cross', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectCrossM1'}],...                                 
        'OutputActions', actions.WaitingAction);    
    sma = AddState(sma, 'Name', 'M2IncorrectFirstCollectM1Cross', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectCrossM1'}],...                                 
        'OutputActions', actions.WaitingAction);    
 %--------------------------------------------------------------------------    
    %FIRST MOUSE POKED, COLLECT SECOND MOUSE CROSS
     sma = AddState(sma, 'Name', 'CollectCrossM1', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'M1CorrectCrossCollectItsPoke'},...
                                 {choices.m1IncorrectCross, 'M1IncorrectCrossCollectItsPoke'},... No one gets reward                                                    
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
     sma = AddState(sma, 'Name', 'CollectCrossM2', ... No one gets reward 
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2correctCross, 'M2CorrectCrossCollectItsPoke'},...
                                 {choices.m2IncorrectCross, 'M2IncorrectCrossCollectItsPoke'},... No one gets reward                                                    
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
%-------------------------------------------------------------------------- 
    %REGISTER SECOND MOUSE CROSS
    sma = AddState(sma, 'Name', 'M1CorrectCrossCollectItsPoke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM1'}],...                                 
        'OutputActions', actions.WaitingAction);
    sma = AddState(sma, 'Name', 'M1IncorrectCrossCollectItsPoke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM1'}],...                                 
        'OutputActions', actions.WaitingAction); 
    sma = AddState(sma, 'Name', 'M2CorrectCrossCollectItsPoke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM2'}],...                                 
        'OutputActions', actions.WaitingAction);    
     sma = AddState(sma, 'Name', 'M2IncorrectCrossCollectItsPoke', ... No one gets reward 
        'Timer',0,...
        'StateChangeConditions',[{'GlobalTimer2_End','customExit'},...
                                 {'Tup','CollectPokeM2'}],...                                 
        'OutputActions', actions.WaitingAction);       
%--------------------------------------------------------------------------     
%BOTH CROSSED CORRECTLY, FIRST REWARDED BUT SECOND MOUSE POKED WRONG
      sma = AddState(sma, 'Name', 'M1Wrong', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'M2RewardedM1Wrong'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);

      sma = AddState(sma, 'Name', 'M2Wrong', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'M1RewardedM2Wrong'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    
    
    %M1WrongWaitM2Cross - if M2 cross correctly, and pokes, he gets reward.FIX
    %No reward possible for M1
    %M2WrongWaitM1Cross


%% A trial will result in 2 possibilities: both rewarded or both punished
sma = AddState(sma, 'Name', 'BothRewarded', ... when second mouse was fast!! usefull!!
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'BothCorrect', ... when second mouse was too slow
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'BothPunished', ...
    'Timer',times.PunishmentTimeout,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', actions.PunishOutputAction);


sma = AddState(sma, 'Name', 'M2RewardedM1Wrong', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'M1RewardedM2Wrong', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});


sma = AddState(sma, 'Name', 'customExit',...
    'Timer',times.ITI,...
    'StateChangeConditions', {'Tup','exit'},...
    'OutputActions',actions.ITIAction);

end