function sma = getTwoMiceStateMachineCompetitiveCooperation(choices,actions,times,conditions)
sma = NewStateMachine();
sma = SetGlobalTimer(sma,...
                     'TimerID', 1,...
                     'Duration', times.StimulusDuration,...
                     'OnsetDelay',0,...
                     'Channel', 'BNC1',...
                     'OnsetValue',1, 'OffsetValue',0);

sma = SetGlobalTimer(sma,...
                     'TimerID', 2,...
                     'Duration', times.DecisionTimeout,...
                     'OnsetDelay',0);
%% 1) START TRIAL
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'Start', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'WaitingforBothMiceStart'},...
    'OutputActions', actions.StartAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforBothMiceStart', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.ZoneChangeCondition, 'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse2', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse2,...
    'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse1', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse1,...
    'OutputActions', actions.WaitingAction); 
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'BothMiceInZone', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'CheckZoneOut'},...
    'OutputActions', actions.StimulusPresentationAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'CheckZoneOut', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', conditions.CheckZoneOut, ...
    'OutputActions', [actions.WaitingAction, {'GlobalTimerTrig', 2}]);  %When one of the mice leave circle, go to BothMiceMakingDecision

%--------------------------------------------------------------------------    
%% 2) CHECK FIRST CROSSING OF START LINE
%% Waiting for the first mice to cross starting line (all states dependent on crossing and not on choice)
    sma = AddState(sma, 'Name', 'BothMiceMakingDecision', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'M1CrossedWaiting'},...
                                 {choices.m2correctCross, 'M2CrossedWaiting'},...
                                 {choices.m1IncorrectCross, 'WrongCross'},...
                                 {choices.m2IncorrectCross, 'WrongCross'},...                                                                   
                                 {'Tup','customExit'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
      sma = AddState(sma, 'Name', 'M1CrossedWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2correctCross, 'ReleaseReward'},... Both mice have crossed, fastest get reward
                                 {choices.m2IncorrectCross, 'WrongCross'},... M2 chose wrong, both lose       
                                 {choices.m1CorrectChoice,  'CorrectM1WaitM2Cross'},... Fastest mouse chose, waiting for second cross or disengagement                                                        
                                 {'Tup','customExit'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);

       sma = AddState(sma, 'Name', 'M2CrossedWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'ReleaseReward'},... Both mice have crossed, fastest get reward
                                 {choices.m2CorrectChoice,  'CorrectM2WaitM1Cross'},... Fastest mouse chose, waiting for second cross or disengagement
                                 {choices.m1IncorrectCross, 'WrongCross'},... M2 chose wrong, both lose                                                                   
                                 {'Tup','customExit'} ...
                                 {'GlobalTimer2_End','customExit'}],...
        'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------    
%% 3) CHECK SECOND CROSSING OF START LINE

    % create timeout No cross

    %both crossed correctly before choice
     sma = AddState(sma, 'Name', 'ReleaseReward', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'RewardM1First'},... 
                                 {choices.m2CorrectChoice,  'RewardM2First'},...
                                 {choices.m1IncorrectChoice,'M1WrongWait'},...
                                 {choices.m2InCorrectChoice,'M2WrongWait'},...                            
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);

    %M1 chose and then M2 crossed correctly OR M2 cross wrong or M2 doesnt cross
     sma = AddState(sma, 'Name', 'CorrectM1WaitM2Cross', ...
        'Timer',times.NoCrossTimeout,...
        'StateChangeConditions',[{choices.m2correctCross, 'RewardM1First'},... Both mice have crossed, fastest get reward
                                 {choices.m2IncorrectCross, 'M2WrongCrossBothPunished'},... M2 chose wrong, both lose                                                                                               
                                 {'Tup','RewardOnlyM1'}],...
        'OutputActions', actions.WaitingAction);

    %M2 chose and then M1 crossed correctly OR M1 cross wrong or M1 doesnt cross
     sma = AddState(sma, 'Name', 'CorrectM2WaitM1Cross', ...
        'Timer',times.NoCrossTimeout,...
        'StateChangeConditions',[{choices.m1correctCross, 'RewardM2First'},... Both mice have crossed, fastest get reward
                                 {choices.m1IncorrectCross, 'M2WrongCrossBothPunished'},... M2 chose wrong, both lose                                                                                              
                                 {'Tup','RewardOnlyM2'}],...
        'OutputActions', actions.WaitingAction);

%--------------------------------------------------------------------------    
%% 4) RELEASE REWARD
    %% Both went to the correct side
    %% M1 First
    sma = AddState(sma, 'Name', 'RewardM1First', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'CorrectM1SoftDelay'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'CorrectM1SoftDelay', ... within the soft delay, both get full reward
        'Timer',times.SoftDelay,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'FullRewardM2'},...
                                  {choices.m2InCorrectChoice,'M2Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','M1CorrectWaiting'}], ...
        'OutputActions', actions.WaitingAction);

    sma = AddState(sma, 'Name', 'FullRewardM2', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'M1CorrectWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m2CorrectChoice, 'RewardM2Second'} ...
                                  {choices.m2InCorrectChoice,'M2Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}], ...
        'OutputActions', actions.WaitingAction);


    %% M2 First
    sma = AddState(sma, 'Name', 'RewardM2First', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'CorrectM2SoftDelay'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'CorrectM2SoftDelay', ... within the soft delay, both get full reward
        'Timer',times.SoftDelay,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'FullRewardM1'},...
                                  {choices.m1IncorrectChoice,'M1Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','M2CorrectWaiting'}], ...
        'OutputActions', actions.WaitingAction);

    sma = AddState(sma, 'Name', 'FullRewardM1', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', [{'GlobalTimer2_End','customExit'},...
                                 {'Tup', 'BothRewarded'}],...
        'OutputActions', [{choices.m2CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'M2CorrectWaiting', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions', [{choices.m1CorrectChoice, 'RewardM1Second'} ...
                                  {choices.m1IncorrectChoice,'M1Wrong'},...
                                  {'GlobalTimer2_End','customExit'},...
                                  {'Tup','customExit'}], ...
        'OutputActions', actions.WaitingAction);

    %% One mouse gave up, reward only first
     sma = AddState(sma, 'Name', 'RewardOnlyM1', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'M1RewardedM2Punished'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

     sma = AddState(sma, 'Name', 'RewardOnlyM2', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'M2RewardedM1Punished'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);


    %% First Mouse Wrong, Second Rewarded (unlikely, but who knows)
    %M2 can get it right
     sma = AddState(sma, 'Name', 'M1WrongWait', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M2RewardedTerminal'},...
                                 {choices.m2InCorrectChoice,'M2WrongTerminal'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);


     sma = AddState(sma, 'Name', 'M2RewardedTerminal', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'M2RewardedM1Wrong'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

     sma = AddState(sma, 'Name', 'M2WrongTerminal', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);

     %M1 can get it right
     sma = AddState(sma, 'Name', 'M2WrongWait', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M1RewardedTerminal'},...
                                 {choices.m2InCorrectChoice,'M1WrongTerminal'},...
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);

      sma = AddState(sma, 'Name', 'M1RewardedTerminal', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'M1RewardedM2Wrong'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);

      sma = AddState(sma, 'Name', 'M1WrongTerminal', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);

    %% Second mouse is slower and gets PercentageRewardSecond

    sma = AddState(sma, 'Name', 'RewardM2Second', ...
        'Timer',choices.m2ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothCorrect'},...
        'OutputActions', [conditions.RewardSecondM2 {'SoftCode',100, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'RewardM1Second', ...
        'Timer',choices.m1ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothCorrect'},...
        'OutputActions', [conditions.RewardSecondM1 {'SoftCode',100, 'AnalogIn1', ['#' 1]} actions.WaitingAction]);

%-------------------------------------------------------------------------- 
%% 5) PUNISH BOTH MICE, BUT COLLECT THEIR CHOICES
    %% One crossed wrong   
    %COLLECT BOTH POKES
    % First mouse crossed wrong collect first poke
    sma = AddState(sma, 'Name', 'WrongCross', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectFirstBothPunished'},...
                                 {choices.m2CorrectChoice,  'M2CorrectFirstBothPunished'},...
                                 {choices.m1IncorrectChoice,  'M1WrongFirstBothPunished'},...
                                 {choices.m2InCorrectChoice,  'M2WrongFirstBothPunished'},...                                 
                                 {'GlobalTimer2_End','customExit'},...
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
    % M1 correct collected, collect second poke
    sma = AddState(sma, 'Name', 'M1CorrectFirstBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M2CorrectSecondBothPunished'},...
                                 {choices.m2InCorrectChoice,  'M2WrongSecondBothPunished'},...
                                 {'GlobalTimer2_End','customExit'},...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    % M1 correct collected, collect second poke
     sma = AddState(sma, 'Name', 'M2CorrectFirstBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectSecondBothPunished'},...
                                 {choices.m1IncorrectChoice,  'M1WrongSecondBothPunished'},...
                                 {'GlobalTimer2_End','customExit'},...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    % M1 correct collected, collect second poke
         sma = AddState(sma, 'Name', 'M1WrongFirstBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M2CorrectSecondBothPunished'},...
                                 {choices.m2InCorrectChoice,  'M2WrongSecondBothPunished'},...
                                 {'GlobalTimer2_End','customExit'},...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    % M1 correct collected, collect second poke
     sma = AddState(sma, 'Name', 'M2WrongFirstBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectSecondBothPunished'},...
                                 {choices.m1IncorrectChoice,  'M1WrongSecondBothPunished'},... M2WrongAfterEnd
                                 {'GlobalTimer2_End','customExit'},...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);

    
  %% Collecting second mouse choice after first wrong mouse - both punished  
    sma = AddState(sma, 'Name', 'M1CorrectSecondBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    sma = AddState(sma, 'Name', 'M2CorrectSecondBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    sma = AddState(sma, 'Name', 'M1WrongSecondBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
    sma = AddState(sma, 'Name', 'M2WrongSecondBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
    
%--------------------------------------------------------------------------  
%% Second wrong both punished
    %COLLECT REMAINING POKE
    %% Second one crossed wrong, both punished    
    % M1 crossed wrong after M2 chose (collect poke M1)
    sma = AddState(sma, 'Name', 'M1WrongCrossBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectSecondBothPunished'},...
                                 {choices.m1IncorrectChoice,  'M1WrongSecondBothPunished'},... M1WrongAfterEnd
                                 {'GlobalTimer2_End','customExit'},...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
     
    % M2 crossed wrong after M1 chose (collect poke M2)
     sma = AddState(sma, 'Name', 'M2WrongCrossBothPunished', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m2CorrectChoice,  'M2CorrectSecondBothPunished'},...
                                 {choices.m2InCorrectChoice,  'M2WrongSecondBothPunished'},... M2WrongAfterEnd
                                 {'GlobalTimer2_End','customExit'},...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
  %--------------------------------------------------------------------------  

  %% improbable - m2 wrong but first rewarded
      sma = AddState(sma, 'Name', 'M1Wrong', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'M2RewardedM1Wrong'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);

      sma = AddState(sma, 'Name', 'M2Wrong', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'M1RewardedM2Wrong'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);


%% A trial will result in 2 possibilities: both rewarded or both punished
sma = AddState(sma, 'Name', 'BothRewarded', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'BothCorrect', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'M1RewardedM2Punished', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'M2RewardedM1Punished', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});
sma = AddState(sma, 'Name', 'BothPunished', ...
    'Timer',times.PunishmentTimeout,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', actions.PunishOutputAction);



sma = AddState(sma, 'Name', 'M2RewardedM1Wrong', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'M1RewardedM2Wrong', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});


sma = AddState(sma, 'Name', 'customExit',...
    'Timer',times.ITI,...
    'StateChangeConditions', {'Tup','exit'},...
    'OutputActions',actions.ITIAction);

end