function sma = getTwoMiceStateMachineCooperation(choices,actions,times,conditions)
sma = NewStateMachine();
sma = SetGlobalTimer(sma,...
                     'TimerID', 1,...
                     'Duration', times.StimulusDuration,...
                     'OnsetDelay',0,...
                     'Channel', 'BNC1',...
                     'OnsetValue',1, 'OffsetValue',0);
%%%%%%%%%%% Start Beatriz Added
sma = SetGlobalTimer(sma,...
                     'TimerID', 2,...
                     'Duration', times.DecisionTimeout,...
                     'OnsetDelay',0);
%                      'Channel', 'none',...
%                      'OnsetValue',1, 'OffsetValue',0);

%%%%%%%%%%% End Beatriz Added
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'Start', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'WaitingforBothMiceStart'},...
    'OutputActions', actions.StartAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforBothMiceStart', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.ZoneChangeCondition, 'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse2', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse2,...
    'OutputActions', actions.WaitingAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'WaitingforMouse1', ...
    'Timer',times.InitiationTimeout,...
    'StateChangeConditions', conditions.WaitingForMouse1,...
    'OutputActions', actions.WaitingAction); 
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'BothMiceInZone', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'CheckZoneOut'},...
    'OutputActions', actions.StimulusPresentationAction);
%--------------------------------------------------------------------------
sma = AddState(sma, 'Name', 'CheckZoneOut', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', conditions.CheckZoneOut, ...
    'OutputActions', [actions.WaitingAction, {'GlobalTimerTrig', 2}]);  %When one of the mice leave circle, go to BothMiceMakingDecision

%START GLOBAL TIMER, afterwards 'Tup', 'customExit'

%% Now add the different choices and outcomes here

%%%%%%%%%%% Start Beatriz Edited
    sma = AddState(sma, 'Name', 'BothMiceMakingDecision', ...
        'Timer',times.DecisionTimeout,...
        'StateChangeConditions',[{choices.m1CorrectChoice,  'M1CorrectWaitingM2'},...
                                 {choices.m2CorrectChoice,  'M2CorrectWaitingM1'},...
                                 conditions.MouseTerminate,...                                 
                                 {'Tup','customExit'}],...
        'OutputActions', actions.WaitingAction);
    
%--------------------------------------------------------------------------    
 %% Waiting for both mice to poke together 
   % here we wait for cooperation

sma = AddState(sma, 'Name', 'M1CorrectWaitingM2', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', [{choices.m2CorrectChoice, 'RewardM1First'},...
                              {choices.OutOfPokeM1, 'CooperationTimewindowM1'},...
                              conditions.MouseTerminate,...
                              {'Tup','customExit'}], ...
    'OutputActions', actions.WaitingAction);
%                              choices.m1CorrectChoice,'M1CorrectWaitingM2',...

sma = AddState(sma, 'Name', 'M2CorrectWaitingM1', ...
    'Timer',times.DecisionTimeout,...
    'StateChangeConditions', [{choices.m1CorrectChoice, 'RewardM2First'},...
                              {choices.OutOfPokeM2, 'CooperationTimewindowM2'},...
                              conditions.MouseTerminate,...
                              {'Tup','customExit'}], ...
    'OutputActions', actions.WaitingAction); 

% Here is the interval after the first mouse stopped poking, when reward will still be released
 sma = AddState(sma, 'Name', 'CooperationTimewindowM1', ...
    'Timer',times.CooperationTimeout,...
    'StateChangeConditions', [{choices.m2CorrectChoice, 'RewardM1First'},...
                              conditions.MouseTerminate,...
                              {'Tup','BothMiceMakingDecision'}], ...
    'OutputActions', actions.WaitingAction);

 sma = AddState(sma, 'Name', 'CooperationTimewindowM2', ...
    'Timer',times.CooperationTimeout,...
    'StateChangeConditions', [{choices.m1CorrectChoice, 'RewardM2First'},...
                              conditions.MouseTerminate,...
                             {'Tup','BothMiceMakingDecision'}], ...
    'OutputActions', actions.WaitingAction);


%--------------------------------------------------------------------------    
    %% Mice cooperated, both are Rewarded.
    %% M1 rewarded first
    sma = AddState(sma, 'Name', 'RewardM1First', ...
        'Timer',choices.m1ValveTime,...
        'StateChangeConditions', {'Tup', 'RewardM2Second'},...
        'OutputActions', [{choices.m1CorrectValve,1,'AnalogIn1', ['#' 1]} actions.WaitingAction]);
    
    sma = AddState(sma, 'Name', 'RewardM2Second', ...
        'Timer',choices.m2ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m2CorrectValve,1,'SoftCode',100, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);

    %% M2 rewarded first
    sma = AddState(sma, 'Name', 'RewardM2First', ...
        'Timer',choices.m2ValveTime,...
        'StateChangeConditions', {'Tup', 'RewardM1Second'},...
        'OutputActions', [{choices.m2CorrectValve,1, 'AnalogIn1', ['#' 2]} actions.WaitingAction]);

    sma = AddState(sma, 'Name', 'RewardM1Second', ...
        'Timer',choices.m1ValveTimeSecond,...
        'StateChangeConditions', {'Tup', 'BothRewarded'},...
        'OutputActions', [{choices.m1CorrectValve,1,'SoftCode',100, 'AnalogIn1', ['#' 1]} actions.WaitingAction]);


    %--------------------------------------------------------------------------  
    %% One wrong, both punished    
    %% M1 Wrong First, BothPunished
    sma = AddState(sma, 'Name', 'M1WrongBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);

    %% M2 Wrong First, BothPunished
    sma = AddState(sma, 'Name', 'M2WrongBothPunished', ...
        'Timer',0,...
        'StateChangeConditions', {'Tup', 'BothPunished'},...
        'OutputActions', [actions.WaitingAction,'SoftCode',100]);
%--------------------------------------------------------------------------  

%% A (performance) trial will result in 4 possibilities: both rewarded, both punished and so on...
sma = AddState(sma, 'Name', 'BothRewarded', ...
    'Timer',0,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', {});

sma = AddState(sma, 'Name', 'BothPunished', ...
    'Timer',times.PunishmentTimeout,...
    'StateChangeConditions', {'Tup', 'customExit'},...
    'OutputActions', actions.PunishOutputAction);

sma = AddState(sma, 'Name', 'customExit',...
    'Timer',times.ITI,...
    'StateChangeConditions', {'Tup','exit'},...
    'OutputActions',actions.ITIAction);
end